### ISSUE TITLE
Новая версия dbibackend 

### ISSUE THREAD

**Issue by rashevskyv** [vKolerts/dbi-nsw#2]
Вышла новая версия бекенда. Не совместима со старой. Работает с DBI 168 и выше. 
[DBI.168.zip](https://github.com/vKolerts/dbi-nsw/files/5395309/DBI.168.zip)

**Comment by vKolerts** [comment]
> Вышла новая версия бекенда. Не совместима со старой. Работает с DBI 168 и выше.
> [DBI.168.zip](https://github.com/vKolerts/dbi-nsw/files/5395309/DBI.168.zip)

Спасибо, гляну на днях

**Comment by rashevskyv** [comment]
Новые версии DBI буду складывать сюда - https://github.com/rashevskyv/dbi/releases/tag/169
С согласия автора, разумеется

**Comment by vKolerts** [comment]
фэнкс
